version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      #mongodb://root:MongoDB2019!@localhost:27017
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - app_network
  # Redis
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - "6379:6379"

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    networks:
      - app_network
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    depends_on:
      - mongo
      - redis

# Volumes
volumes:
  mongo_data: {}
  redis_data: {}
  portainer_data: {} 
# Redes
networks:
  app_network:
    driver: bridge
